package com.fracta7.crafter.model

fun itemInit(): List<Item> {
    return listOf(
        Item(id = "stone", name = "Stone", stackSize = 64, raw = true),
        Item(id = "granite", name = "Granite", stackSize = 64, raw = true),
        Item(id = "polished_granite", name = "Polished Granite", stackSize = 64, raw = false),
        Item(id = "diorite", name = "Diorite", stackSize = 64, raw = true),
        Item(id = "polished_diorite", name = "Polished Diorite", stackSize = 64, raw = false),
        Item(id = "andesite", name = "Andesite", stackSize = 64, raw = true),
        Item(id = "polished_andesite", name = "Polished Andesite", stackSize = 64, raw = false),
        Item(id = "deepslate", name = "Deepslate", stackSize = 64, raw = true),
        Item(id = "cobbled_deepslate", name = "Cobbled Deepslate", stackSize = 64, raw = true),
        Item(id = "polished_deepslate", name = "Polished Deepslate", stackSize = 64, raw = false),
        Item(id = "calcite", name = "Calcite", stackSize = 64, raw = true),
        Item(id = "tuff", name = "Tuff", stackSize = 64, raw = true),
        Item(id = "dripstone_block", name = "Dripstone Block", stackSize = 64, raw = true),
        Item(id = "grass_block", name = "Grass Block", stackSize = 64, raw = true),
        Item(id = "dirt", name = "Dirt", stackSize = 64, raw = true),
        Item(id = "coarse_dirt", name = "Coarse Dirt", stackSize = 64, raw = false),
        Item(id = "podzol", name = "Podzol", stackSize = 64, raw = true),
        Item(id = "rooted_dirt", name = "Rooted Dirt", stackSize = 64, raw = true),
        Item(id = "crimson_nylium", name = "Crimson Nylium", stackSize = 64, raw = true),
        Item(id = "warped_nylium", name = "Warped Nylium", stackSize = 64, raw = true),
        Item(id = "cobblestone", name = "Cobblestone", stackSize = 64, raw = true),
        Item(id = "oak_planks", name = "Oak Planks", stackSize = 64, raw = false),
        Item(id = "spruce_planks", name = "Spruce Planks", stackSize = 64, raw = false),
        Item(id = "birch_planks", name = "Birch Planks", stackSize = 64, raw = false),
        Item(id = "jungle_planks", name = "Jungle Planks", stackSize = 64, raw = false),
        Item(id = "acacia_planks", name = "Acacia Planks", stackSize = 64, raw = false),
        Item(id = "dark_oak_planks", name = "Dark Oak Planks", stackSize = 64, raw = false),
        Item(id = "crimson_planks", name = "Crimson Planks", stackSize = 64, raw = false),
        Item(id = "warped_planks", name = "Warped Planks", stackSize = 64, raw = false),
        Item(id = "oak_sapling", name = "Oak Sapling", stackSize = 64, raw = true),
        Item(id = "spruce_sapling", name = "Spruce Sapling", stackSize = 64, raw = true),
        Item(id = "birch_sapling", name = "Birch Sapling", stackSize = 64, raw = true),
        Item(id = "jungle_sapling", name = "Jungle Sapling", stackSize = 64, raw = true),
        Item(id = "acacia_sapling", name = "Acacia Sapling", stackSize = 64, raw = true),
        Item(id = "dark_oak_sapling", name = "Dark Oak Sapling", stackSize = 64, raw = true),
        Item(id = "bedrock", name = "Bedrock", stackSize = 64, raw = true),
        Item(id = "sand", name = "Sand", stackSize = 64, raw = true),
        Item(id = "red_sand", name = "Red Sand", stackSize = 64, raw = true),
        Item(id = "gravel", name = "Gravel", stackSize = 64, raw = true),
        Item(id = "coal_ore", name = "Coal Ore", stackSize = 64, raw = true),
        Item(id = "deepslate_coal_ore", name = "Deepslate Coal Ore", stackSize = 64, raw = true),
        Item(id = "iron_ore", name = "Iron Ore", stackSize = 64, raw = true),
        Item(id = "deepslate_iron_ore", name = "Deepslate Iron Ore", stackSize = 64, raw = true),
        Item(id = "copper_ore", name = "Copper Ore", stackSize = 64, raw = true),
        Item(id = "deepslate_copper_ore", name = "Deepslate Copper Ore", stackSize = 64, raw = true),
        Item(id = "gold_ore", name = "Gold Ore", stackSize = 64, raw = true),
        Item(id = "deepslate_gold_ore", name = "Gold Deepslate Ore", stackSize = 64, raw = true),
        Item(id = "redstone_ore", name = "Redstone Ore", stackSize = 64, raw = true),
        Item(id = "deepslate_redstone_ore", name = "Deepslate Redstone Ore", stackSize = 64, raw = true),
        Item(id = "emerald_ore", name = "Emerald Ore", stackSize = 64, raw = true),
        Item(id = "deepslate_emerald_ore", name = "Deepslate Emerald Ore", stackSize = 64, raw = true),
        Item(id = "lapis_ore", name = "Lapis Lazuli Ore", stackSize = 64, raw = true),
        Item(id = "deepslate_lapis_ore", name = "Deepslate Lapis Lazuli Ore", stackSize = 64, raw = true),
        Item(id = "diamond_ore", name = "Diamond Ore", stackSize = 64, raw = true),
        Item(id = "deepslate_diamond_ore", name = "Deepslate Diamond Ore", stackSize = 64, raw = true),
        Item(id = "nether_gold_ore", name = "Nether Gold Ore", stackSize = 64, raw = true),
        Item(id = "nether_quartz_ore", name = "Nether Quartz Ore", stackSize = 64, raw = true),
        Item(id = "ancient_debris", name = "Ancient Debris", stackSize = 64, raw = true),
        Item(id = "coal_block", name = "Block of Coal", stackSize = 64, raw = false),
        Item(id = "raw_iron_block", name = "Block of Raw Iron", stackSize = 64, raw = false),
        Item(id = "raw_copper_block", name = "Block of Raw Copper", stackSize = 64, raw = false),
        Item(id = "raw_gold_block", name = "Block of Raw Gold", stackSize = 64, raw = false),
        Item(id = "amethyst_block", name = "Block of Amethyst", stackSize = 64, raw = false),
        Item(id = "budding_amethyst", name = "Budding Amethyst", stackSize = 64, raw = true),
        Item(id = "iron_block", name = "Block of Iron", stackSize = 64, raw = false),
        Item(id = "copper_block", name = "Block of Copper", stackSize = 64, raw = false),
        Item(id = "gold_block", name = "Block of Gold", stackSize = 64, raw = false),
        Item(id = "diamond_block", name = "Block of Diamond", stackSize = 64, raw = false),
        Item(id = "netherite_block", name = "Netherite Block", stackSize = 64, raw = false),
        Item(id = "exposed_copper", name = "Exposed Copper", stackSize = 64, raw = false),
        Item(id = "weathered_copper", name = "Weather Copper", stackSize = 64, raw = false),
        Item(id = "oxidized_copper", name = "Oxidized Copper", stackSize = 64, raw = false),
        Item(id = "cut_copper", name = "Cut Copper", stackSize = 64, raw = false),
        Item(id = "exposed_cut_copper", name = "Exposed Cut Copper", stackSize = 64, raw = false),
        Item(id = "weathered_cut_copper", name = "Weathered Cut Copper", stackSize = 64, raw = false),
        Item(id = "oxidized_cut_copper", name = "Oxidized Cut Copper", stackSize = 64, raw = false),
        Item(id = "cut_copper_stairs", name = "Cut Copper Stairs", stackSize = 64, raw = false),
        Item(id = "exposed_cut_copper_stairs", name = "Exposed Cut Copper Stairs", stackSize = 64, raw = false),
        Item(id = "weathered_cut_copper_stairs", name = "Weathered Cut Copper Stairs", stackSize = 64, raw = false),
        Item(id = "oxidized_cut_copper_stairs", name = "Oxidized Cut Copper Stairs", stackSize = 64, raw = false),
        Item(id = "cut_copper_slab", name = "Cut Copper Slab", stackSize = 64, raw = false),
        Item(id = "exposed_cut_copper_slab", name = "Exposed Cut Copper Slab", stackSize = 64, raw = false),
        Item(id = "weathered_cut_copper_slab", name = "Weathered Cut Copper Slab", stackSize = 64, raw = false),
        Item(id = "oxidized_cut_copper_slab", name = "Oxidized Cut Copper Slab", stackSize = 64, raw = false),
        Item(id = "waxed_copper_block", name = "Waxed Block of Copper", stackSize = 64, raw = false),
        Item(id = "waxed_exposed_copper", name = "Waxed Exposed Copper", stackSize = 64, raw = false),
        Item(id = "waxed_weathered_copper", name = "Waxed Weather Copper", stackSize = 64, raw = false),
        Item(id = "waxed_oxidized_copper", name = "Waxed Oxidized Copper", stackSize = 64, raw = false),
        Item(id = "waxed_cut_copper", name = "Waxed Cut Copper", stackSize = 64, raw = false),
        Item(id = "waxed_exposed_cut_copper", name = "Waxed Exposed Cut Copper", stackSize = 64, raw = false),
        Item(id = "waxed_weathered_cut_copper", name = "Waxed Weathered Cut Copper", stackSize = 64, raw = false),
        Item(id = "waxed_oxidized_cut_copper", name = "Waxed Oxidized Cut Copper", stackSize = 64, raw = false),
        Item(id = "waxed_cut_copper_stairs", name = "Waxed Cut Copper Stairs", stackSize = 64, raw = false),
        Item(id = "waxed_exposed_cut_copper_stairs", name = "Waxed Exposed Cut Copper Stairs", stackSize = 64, raw = false),
        Item(id = "waxed_weathered_cut_copper_stairs", name = "Waxed Weathered Cut Copper Stairs", stackSize = 64, raw = false),
        Item(id = "waxed_oxidized_cut_copper_stairs", name = "Waxed Oxidized Cut Copper Stairs", stackSize = 64, raw = false),
        Item(id = "waxed_cut_copper_slab", name = "Waxed Cut Copper Slab", stackSize = 64, raw = false),
        Item(id = "waxed_exposed_cut_copper_slab", name = "Waxed Exposed Cut Copper Slab", stackSize = 64, raw = false),
        Item(id = "waxed_weathered_cut_copper_slab", name = "Waxed Weathered Cut Copper Slab", stackSize = 64, raw = false),
        Item(id = "waxed_oxidized_cut_copper_slab", name = "Waxed Oxidized Cut Copper Slab", stackSize = 64, raw = false),
        Item(id = "oak_log", name = "Oak Log", stackSize = 64, raw = true),
        Item(id = "spruce_log", name = "Spruce Log", stackSize = 64, raw = true),
        Item(id = "birch_log", name = "Birch Log", stackSize = 64, raw = true),
        Item(id = "jungle_log", name = "Jungle Log", stackSize = 64, raw = true),
        Item(id = "acacia_log", name = "Acacia Log", stackSize = 64, raw = true),
        Item(id = "dark_oak_log", name = "Dark Oak Log", stackSize = 64, raw = true),
        Item(id = "crimson_stem", name = "Crimson Stem", stackSize = 64, raw = true),
        Item(id = "warped_stem", name = "Warped Stem", stackSize = 64, raw = true),
        Item(id = "stripped_oak_log", name = "Stripped Oak Log", stackSize = 64, raw = false),
        Item(id = "stripped_spruce_log", name = "Stripped Spruce Log", stackSize = 64, raw = false),
        Item(id = "stripped_birch_log", name = "Stripped Birch Log", stackSize = 64, raw = false),
        Item(id = "stripped_jungle_log", name = "Stripped Jungle Log", stackSize = 64, raw = false),
        Item(id = "stripped_acacia_log", name = "Stripped Acacia Log", stackSize = 64, raw = false),
        Item(id = "stripped_dark_oak_log", name = "Stripped Dark Oak Log", stackSize = 64, raw = false),
        Item(id = "stripped_crimson_stem", name = "Stripped_crimson_stem", stackSize = 64, raw = false),
        Item(id = "stripped_warped_stem", name = "Stripped Warped Stem", stackSize = 64, raw = false),
        Item(id = "stripped_oak_wood", name = "Stripped Oak Wood", stackSize = 64, raw = false),
        Item(id = "stripped_spruce_wood", name = "Stripped Spruce Wood", stackSize = 64, raw = false),
        Item(id = "stripped_birch_wood", name = "Stripped Birch Wood", stackSize = 64, raw = false),
        Item(id = "stripped_jungle_wood", name = "Stripped Jungle Wood", stackSize = 64, raw = false),
        Item(id = "stripped_acacia_wood", name = "Stripped Acacia Wood", stackSize = 64, raw = false),
        Item(id = "stripped_dark_oak_wood", name = "Stripped Dark Oak Wood", stackSize = 64, raw = false),
        Item(id = "stripped_crimson_hyphae", name = "Stripped Crimson Hyphae", stackSize = 64, raw = false),
        Item(id = "stripped_warped_hyphae", name = "Stripped Warped Hyphae", stackSize = 64, raw = false),
        Item(id = "oak_wood", name = "Oak Wood", stackSize = 64, raw = false),
        Item(id = "spruce_wood", name = "Spruce Wood", stackSize = 64, raw = false),
        Item(id = "birch_wood", name = "Birch Wood", stackSize = 64, raw = false),
        Item(id = "jungle_wood", name = "Jungle Wood", stackSize = 64, raw = false),
        Item(id = "acacia_wood", name = "Acacia Wood", stackSize = 64, raw = true),
        Item(id = "dark_oak_wood", name = "Dark Oak Wood", stackSize = 64, raw = false),
        Item(id = "crimson_hyphae", name = "crimson_hyphae", stackSize = 64, raw = false),
        Item(id = "warped_hyphae", name = "Warped Hyphae", stackSize = 64, raw = false),
        Item(id = "oak_leaves", name = "Oak Leaves", stackSize = 64, raw = true),
        Item(id = "spruce_leaves", name = "Spruce Leaves", stackSize = 64, raw = true),
        Item(id = "birch_leaves", name = "Birch Leaves", stackSize = 64, raw = true),
        Item(id = "acacia_leaves", name = "Acacia Leaves", stackSize = 64, raw = true),
        Item(id = "jungle_leaves", name = "Jungle Leaves", stackSize = 64, raw = true),
        Item(id = "dark_oak_leaves", name = "Dark Oak Leaves", stackSize = 64, raw = true),
        Item(id = "azalea_leaves", name = "Azalea Leaves", stackSize = 64, raw = true),
        Item(id = "flowering_azalea_leaves", name = "Flowering Azalea Leaves", stackSize = 64, raw = true),
        Item(id = "sponge", name = "Sponge", stackSize = 64, raw = true),
        Item(id = "wet_sponge", name = "Wet Sponge", stackSize = 64, raw = true),
        Item(id = "glass", name = "Glass", stackSize = 64, raw = false),
        Item(id = "tinted_glass", name = "Tinted Glass", stackSize = 64, raw = false),
        Item(id = "lapis_block", name = "Block of Lapis Lazuli", stackSize = 64, raw = false),
        Item(id = "sandstone", name = "Sandstone", stackSize = 64, raw = false),
        Item(id = "chiseled_sandstone", name = "Chiseled Sandstone", stackSize = 64, raw = false),
        Item(id = "cut_sandstone", name = "Cut Sandstone", stackSize = 64, raw = false),
        Item(id = "cobweb", name = "Cobweb", stackSize = 64, raw = true),
        Item(id = "grass", name = "Grass", stackSize = 64, raw = true),
        Item(id = "fern", name = "Fern", stackSize = 64, raw = true),
        Item(id = "azalea", name = "Azalea", stackSize = 64, raw = true),
        Item(id = "flowering_azalea", name = "Flowering Azalea", stackSize = 64, raw = true),
        Item(id = "dead_bush", name = "Dead Bush", stackSize = 64, raw = true),
        Item(id = "seagrass", name = "Seagrass", stackSize = 64, raw = true),
        Item(id = "sea_pickle", name = "Sea Pickle", stackSize = 64, raw = true),
        Item(id = "white_wool", name = "White Wool", stackSize = 64, raw = true),
        Item(id = "orange_wool", name = "Orange Wool", stackSize = 64, raw = false),
        Item(id = "magenta_wool", name = "Magenta_wool", stackSize = 64, raw = false),
        Item(id = "light_blue_wool", name = "Light Blue Wool", stackSize = 64, raw = false),
        Item(id = "yellow_wool", name = "Yellow Wool", stackSize = 64, raw = false),
        Item(id = "lime_wool", name = "Lime Wool", stackSize = 64, raw = false),
        Item(id = "pink_wool", name = "Pink Wool", stackSize = 64, raw = false),
        Item(id = "gray_wool", name = "Gray Wool", stackSize = 64, raw = false),
        Item(id = "light_gray_wool", name = "Light Gray Wool", stackSize = 64, raw = false),
        Item(id = "cyan_wool", name = "Cyan Wool", stackSize = 64, raw = false),
        Item(id = "purple_wool", name = "Purple Wool", stackSize = 64, raw = false),
        Item(id = "blue_wool", name = "Blue Wool", stackSize = 64, raw = false),
        Item(id = "brown_wool", name = "Brown Wool", stackSize = 64, raw = false),
        Item(id = "green_wool", name = "Green Wool", stackSize = 64, raw = false),
        Item(id = "red_wool", name = "Red Wool", stackSize = 64, raw = false),
        Item(id = "black_wool", name = "Black Wool", stackSize = 64, raw = false),
        Item(id = "dandelion", name = "Dandelion", stackSize = 64, raw = true),
        Item(id = "poppy", name = "Poppy", stackSize = 64, raw = true),
        Item(id = "blue_orchid", name = "Blue Orchid", stackSize = 64, raw = true),
        Item(id = "allium", name = "Allium", stackSize = 64, raw = true),
        Item(id = "azure_bluet", name = "Azure Bluet", stackSize = 64, raw = true),
        Item(id = "red_tulip", name = "Red Tulip", stackSize = 64, raw = true),
        Item(id = "orange_tulip", name = "Orange Tulip", stackSize = 64, raw = true),
        Item(id = "white_tulip", name = "White Tulip", stackSize = 64, raw = true),
        Item(id = "pink_tulip", name = "Pink Tulip", stackSize = 64, raw = true),
        Item(id = "oxeye_daisy", name = "Oxeye Daisy", stackSize = 64, raw = true),
        Item(id = "cornflower", name = "Cornflower", stackSize = 64, raw = true),
        Item(id = "lily_of_the_valley", name = "Lily of the Valley", stackSize = 64, raw = true),
        Item(id = "wither_rose", name = "Wither Rose", stackSize = 64, raw = true),
        Item(id = "spore_blossom", name = "Spore Blossom", stackSize = 64, raw = true),
        Item(id = "brown_mushroom", name = "Brown Mushroom", stackSize = 64, raw = true),
        Item(id = "red_mushroom", name = "Red Mushroom", stackSize = 64, raw = true),
        Item(id = "crimson_fungus", name = "Crimson Fungus", stackSize = 64, raw = true),
        Item(id = "warped_fungus", name = "Warped Fungus", stackSize = 64, raw = true),
        Item(id = "crimson_roots", name = "Crimson Roots", stackSize = 64, raw = true),
        Item(id = "warped_roots", name = "Warped Roots", stackSize = 64, raw = true),
        Item(id = "nether_sprouts", name = "Nether Sprouts", stackSize = 64, raw = true),
        Item(id = "weeping_vines", name = "Weeping Vines", stackSize = 64, raw = true),
        Item(id = "twisting_vines", name = "Twisting Vines", stackSize = 64, raw = true),
        Item(id = "sugarcane", name = "Sugarcane", stackSize = 64, raw = true),
        Item(id = "kelp", name = "Kelp", stackSize = 64, raw = true),
        Item(id = "moss_carpet", name = "Moss Carpet", stackSize = 64, raw = false),
        Item(id = "moss_block", name = "Moss Block", stackSize = 64, raw = true),
        Item(id = "hanging_roots", name = "Hanging Roots", stackSize = 64, raw = true),
        Item(id = "big_dripleaf", name = "Big Dripleaf", stackSize = 64, raw = true),
        Item(id = "small_dripleaf", name = "Small Dripleaf", stackSize = 64, raw = true),
        Item(id = "bamboo", name = "Bamboo", stackSize = 64, raw = true),
        Item(id = "oak_slab", name = "Oak Slab", stackSize = 64, raw = false),
        Item(id = "spruce_slab", name = "Spruce Slab", stackSize = 64, raw = false),
        Item(id = "birch_slab", name = "Birch Slab", stackSize = 64, raw = false),
        Item(id = "jungle_slab", name = "Jungle Slab", stackSize = 64, raw = false),
        Item(id = "acacia_slab", name = "Acacia Slab", stackSize = 64, raw = false),
        Item(id = "dark_oak_slab", name = "Dark Oak Slab", stackSize = 64, raw = false),
        Item(id = "crimson_slab", name = "Crimson Slab", stackSize = 64, raw = false),
        Item(id = "warped_slab", name = "Warped Slab", stackSize = 64, raw = false),
        Item(id = "stone_slab", name = "Stone Slab", stackSize = 64, raw = false),
        Item(id = "smooth_stone_slab", name = "Smooth Stone Slab", stackSize = 64, raw = false),
        Item(id = "sandstone_slab", name = "Sandstone Slab", stackSize = 64, raw = false),
        Item(id = "cut_sandstone_slab", name = "Cut Sandstone Slab", stackSize = 64, raw = false),
        Item(id = "cobblestone_slab", name = "Cobblestone Slab", stackSize = 64, raw = false),
        Item(id = "brick_slab", name = "Brick Slab", stackSize = 64, raw = false),
        Item(id = "stone_brick_slab", name = "Stone Brick Slab", stackSize = 64, raw = false),
        Item(id = "nether_brick_slab", name = "Nether Brick Slab", stackSize = 64, raw = false),
        Item(id = "quartz_slab", name = "Quartz Slab", stackSize = 64, raw = false),
        Item(id = "red_sandstone_slab", name = "Red Sandstone Slab", stackSize = 64, raw = false),
        Item(id = "cut_red_sandstone_slab", name = "Cut Red Sandstone Slab", stackSize = 64, raw = false),
        Item(id = "purpur_slab", name = "Purpur Slab", stackSize = 64, raw = false),
        Item(id = "prismarine_slab", name = "Prismarine Slab", stackSize = 64, raw = false),
        Item(id = "prismarine_brick_slab", name = "Prismarine Brick Slab", stackSize = 64, raw = false),
        Item(id = "dark_prismarine_slab", name = "Dark Prismarine Slab", stackSize = 64, raw = false),
        Item(id = "smooth_quartz_block", name = "Smooth Quartz Block", stackSize = 64, raw = false),
        Item(id = "smooth_red_sandstone", name = "Smooth Red Sandstone", stackSize = 64, raw = false),
        Item(id = "smooth_sandstone", name = "Smooth Sandstone", stackSize = 64, raw = false),
        Item(id = "smooth_stone", name = "Smooth Stone", stackSize = 64, raw = false),
        Item(id = "bricks", name = "Bricks", stackSize = 64, raw = false),
        Item(id = "bookshelf", name = "Bookshelf", stackSize = 64, raw = false),
        Item(id = "mossy_cobblestone", name = "Mossy Cobblestone", stackSize = 64, raw = false),
        Item(id = "obsidian", name = "Obsidian", stackSize = 64, raw = true),
        Item(id = "torch", name = "Torch", stackSize = 64, raw = false),
        Item(id = "end_rod", name = "End Rod", stackSize = 64, raw = false),
        Item(id = "chorus_plant", name = "Chorus Plant", stackSize = 64, raw = true),
        Item(id = "chorus_flower", name = "Chorus Flower", stackSize = 64, raw = true),
        Item(id = "purpur_block", name = "Purpur Block", stackSize = 64, raw = false),
        Item(id = "purpur_pillar", name = "Purpur Pillar", stackSize = 64, raw = false),
        Item(id = "purpur_stairs", name = "Purpur Stairs", stackSize = 64, raw = false),
        Item(id = "oak_stairs", name = "Oak Stairs", stackSize = 64, raw = false),
        Item(id = "chest", name = "Chest", stackSize = 64, raw = false),
        Item(id = "crafting_table", name = "Crafting Table", stackSize = 64, raw = false),
        Item(id = "farmland", name = "Farmland", stackSize = 64, raw = true),
        Item(id = "furnace", name = "Furnace", stackSize = 64, raw = false),
        Item(id = "ladder", name = "Ladder", stackSize = 64, raw = false),
        Item(id = "cobblestone_stairs", name = "Cobblestone Stairs", stackSize = 64, raw = false),
        Item(id = "snow", name = "Snow", stackSize = 64, raw = false),
        Item(id = "ice", name = "Ice", stackSize = 64, raw = true),
        Item(id = "snow_block", name = "Snow Block", stackSize = 64, raw = false),
        Item(id = "cactus", name = "Cactus", stackSize = 64, raw = true),
        Item(id = "clay", name = "Clay", stackSize = 64, raw = false),
        Item(id = "jukebox", name = "Jukebox", stackSize = 64, raw = false),
        Item(id = "oak_fence", name = "Oak Fence", stackSize = 64, raw = false),
        Item(id = "spruce_fence", name = "Spruce Fence", stackSize = 64, raw = false),
        Item(id = "birch_fence", name = "Birch Fence", stackSize = 64, raw = false),
        Item(id = "jungle_fence", name = "Jungle Fence", stackSize = 64, raw = false),
        Item(id = "acacia_fence", name = "Acacia Fence", stackSize = 64, raw = false),
        Item(id = "dark_oak_fence", name = "Dark Oak Fence", stackSize = 64, raw = false),
        Item(id = "crimson_fence", name = "Crimson Fence", stackSize = 64, raw = false),
        Item(id = "warped_fence", name = "Warped Fence", stackSize = 64, raw = false),
        Item(id = "pumpkin", name = "Pumpkin", stackSize = 64, raw = true),
        Item(id = "carved_pumpkin", name = "Carved Pumpkin", stackSize = 64, raw = false),
        Item(id = "jack_o_lantern", name = "Jack o'Lantern", stackSize = 64, raw = false),
        Item(id = "netherrack", name = "Netherrack", stackSize = 64, raw = true),
        Item(id = "soul_soil", name = "Soul Soil", stackSize = 64, raw = true),
        Item(id = "soul_sand", name = "Soul Sand", stackSize = 64, raw = true),
        Item(id = "basalt", name = "Basalt", stackSize = 64, raw = true),
        Item(id = "polished_basalt", name = "Polished Basalt", stackSize = 64, raw = false),
        Item(id = "smooth_basalt", name = "Smooth Basalt", stackSize = 64, raw = false),
        Item(id = "soul_torch", name = "Soul Torch", stackSize = 64, raw = false),
        Item(id = "glowstone", name = "Glowstone", stackSize = 64, raw = false),
        Item(id = "infested_stone", name = "Infested Stone", stackSize = 64, raw = true),
        Item(id = "infested_cobblestone", name = "Infested Cobblestone", stackSize = 64, raw = true),
        Item(id = "infested_stone_bricks", name = "Infested Stone Bricks", stackSize = 64, raw = true),
        Item(id = "infested_mossy_stone_bricks", name = "Infested Mossy Stone Bricks", stackSize = 64, raw = true),
        Item(id = "infested_cracked_stone_bricks", name = "Infested Cracked Stone Bricks", stackSize = 64, raw = true),
        Item(id = "infested_chiseled_stone_bricks", name = "Infested Chiseled Stone Bricks", stackSize = 64, raw = true),
        Item(id = "infested_deepslate", name = "Infested Deepslate", stackSize = 64, raw = true),
        Item(id = "infested_stone_bricks", name = "Infested Stone Bricks", stackSize = 64, raw = true),
        Item(id = "mossy_stone_bricks", name = "Mossy Stone Bricks", stackSize = 64, raw = false),
        Item(id = "cracked_stone_bricks", name = "Cracked Stone Bricks", stackSize = 64, raw = false),
        Item(id = "chiseled_stone_bricks", name = "Chiseled Stone Bricks", stackSize = 64, raw = false),
        Item(id = "deepslate_bricks", name = "Deepslate Bricks", stackSize = 64, raw = false),
        Item(id = "cracked_deepslate_bricks", name = "Cracked Deepslate Bricks", stackSize = 64, raw = false),
        Item(id = "deepslate_tiles", name = "Deepslate Tiles", stackSize = 64, raw = false),
        Item(id = "cracked_deepslate_tiles", name = "Cracked Deepslate Tiles", stackSize = 64, raw = false),
        Item(id = "chiseled_deepslate", name = "Chiseled Deepslate", stackSize = 64, raw = false),
        Item(id = "brown_mushroom_block", name = "Brown Mushroom Block", stackSize = 64, raw = true),
        Item(id = "red_mushroom_block", name = "Red Mushroom Block", stackSize = 64, raw = true),
        Item(id = "mushroom_stem", name = "Mushroom Stem", stackSize = 64, raw = true),
        Item(id = "iron_bars", name = "Iron Bars", stackSize = 64, raw = false),
        Item(id = "chain", name = "Chain", stackSize = 64, raw = false),
        Item(id = "glass_pane", name = "Glass Pane", stackSize = 64, raw = false),
        Item(id = "melon", name = "Melon", stackSize = 64, raw = false),
        Item(id = "vines", name = "Vines", stackSize = 64, raw = true),
        Item(id = "glow_lichen", name = "Glow Lichen", stackSize = 64, raw = true),
        Item(id = "brick_chair", name = "Brick Chair", stackSize = 64, raw = false),
        Item(id = "stone_brick_stairs", name = "Stone Brick Stairs", stackSize = 64, raw = false),
        Item(id = "mycelium", name = "Mycelium", stackSize = 64, raw = true),
        Item(id = "lily_pad", name = "Lily Pad", stackSize = 64, raw = true),
        Item(id = "nether_bricks", name = "Nether Bricks", stackSize = 64, raw = false),
        Item(id = "cracked_nether_bricks", name = "Cracked Nether Bricks", stackSize = 64, raw = false),
        Item(id = "chiseled_nether_bricks", name = "Chiseled Nether Bricks", stackSize = 64, raw = false),
        Item(id = "nether_brick_fence", name = "Nether Brick Fence", stackSize = 64, raw = false),
        Item(id = "nether_brick_stairs", name = "Nether Brick Stairs", stackSize = 64, raw = false),
        Item(id = "enchanting_table", name = "Enchanting Table", stackSize = 64, raw = false),
        Item(id = "end_portal_frame", name = "End Portal Frame", stackSize = 64, raw = true),
        Item(id = "end_stone", name = "End Stone", stackSize = 64, raw = true),
        Item(id = "end_stone_bricks", name = "End Stone Bricks", stackSize = 64, raw = false),
        Item(id = "sandstone_stairs", name = "Sandstone Stairs", stackSize = 64, raw = false),
        Item(id = "ender_chest", name = "Ender Chest", stackSize = 64, raw = false),
        Item(id = "emerald_block", name = "Block of Emerald", stackSize = 64, raw = false),
        Item(id = "spruce_stairs", name = "Spruce Stairs", stackSize = 64, raw = false),
        Item(id = "birch_stairs", name = "Birch Stairs", stackSize = 64, raw = false),
        Item(id = "jungle_stairs", name = "Jungle Stairs", stackSize = 64, raw = false),
        Item(id = "crimson_stairs", name = "Crimson Stairs", stackSize = 64, raw = false),
        Item(id = "warped_stairs", name = "Warped Stairs", stackSize = 64, raw = false),
        Item(id = "beacon", name = "Beacon", stackSize = 64, raw = false),
        Item(id = "cobblestone_wall", name = "Cobblestone Wall", stackSize = 64, raw = false),
        Item(id = "mossy_cobblestone_wall", name = "Mossy Cobblestone Wall", stackSize = 64, raw = false),
        Item(id = "brick_wall", name = "Brick Wall", stackSize = 64, raw = false),
        Item(id = "prismarine_wall", name = "Prismarine Wall", stackSize = 64, raw = false),
        Item(id = "red_sandstone_wall", name = "Red Sandstone Wall", stackSize = 64, raw = false),
        Item(id = "mossy_stone_brick_wall", name = "Mossy Stone Brick Wall", stackSize = 64, raw = false),
        Item(id = "granite_wall", name = "Granite Wall", stackSize = 64, raw = false),
        Item(id = "stone_brick_wall", name = "Stone Brick Wall", stackSize = 64, raw = false),
        Item(id = "nether_brick_wall", name = "Nether Brick Wall", stackSize = 64, raw = false),
        Item(id = "andesite_wall", name = "Andesite Wall", stackSize = 64, raw = false),
        Item(id = "red_nether_brick_wall", name = "Red Nether Brick Wall", stackSize = 64, raw = false),
        Item(id = "sandstone_wall", name = "Sandstone Wall", stackSize = 64, raw = false),
        Item(id = "end_stone_brick_wall", name = "End Stone Brick Wall", stackSize = 64, raw = false),
        Item(id = "diorite_wall", name = "Diorite Wall", stackSize = 64, raw = false),
        Item(id = "blackstone_wall", name = "Blackstone Wall", stackSize = 64, raw = false),
        Item(id = "polished_blackstone_wall", name = "Polished Blackstone Wall", stackSize = 64, raw = false),
        Item(id = "polished_blackstone_brick_wall", name = "Polished Blackstone Brick Wall", stackSize = 64, raw = false),
        Item(id = "cobbled_deepslate_wall", name = "Cobbled Deepslate Wall", stackSize = 64, raw = false),
        Item(id = "polished_deepslate_wall", name = "Polished Deepslate Wall", stackSize = 64, raw = false),
        Item(id = "deepslate_brick_wall", name = "Deepslate Brick Wall", stackSize = 64, raw = false),
        Item(id = "deepslate_tile_wall", name = "Deepslate Tile Wall", stackSize = 64, raw = false),
        Item(id = "anvil", name = "Anvil", stackSize = 64, raw = false),
        Item(id = "chiseled_quartz_block", name = "Chiseled Quartz Block", stackSize = 64, raw = false),
        Item(id = "quartz_block", name = "Block of Quartz", stackSize = 64, raw = false),
        Item(id = "quartz_bricks", name = "Quartz Bricks", stackSize = 64, raw = false),
        Item(id = "quartz_pillar", name = "Quartz Pillar", stackSize = 64, raw = false),
        Item(id = "quartz_stairs", name = "Quartz Stairs", stackSize = 64, raw = false),
        Item(id = "white_terracotta", name = "White Terracotta", stackSize = 64, raw = false),
        Item(id = "orange_terracotta", name = "Orange Terracotta", stackSize = 64, raw = false),
        Item(id = "magenta_terracotta", name = "Magenta Terracotta", stackSize = 64, raw = false),
        Item(id = "light_blue_terracotta", name = "Light Blue Terracotta", stackSize = 64, raw = false),
        Item(id = "yellow_terracotta", name = "Yellow Terracotta", stackSize = 64, raw = false),
        Item(id = "lime_terracotta", name = "Lime Terracotta", stackSize = 64, raw = false),
        Item(id = "pink_terracotta", name = "Pink Terracotta", stackSize = 64, raw = false),
        Item(id = "gray_terracotta", name = "Gray Terracotta", stackSize = 64, raw = false),
        Item(id = "light_gray_terracotta", name = "Light Gray Terracotta", stackSize = 64, raw = false),
        Item(id = "cyan_terracotta", name = "Cyan Terracotta", stackSize = 64, raw = false),
        Item(id = "purple_terracotta", name = "Purple Terracotta", stackSize = 64, raw = false),
        Item(id = "blue_terracotta", name = "Blue Terracotta", stackSize = 64, raw = false),
        Item(id = "brown_terracotta", name = "Brown Terracotta", stackSize = 64, raw = false),
        Item(id = "green_terracotta", name = "Green Terracotta", stackSize = 64, raw = false),
        Item(id = "red_terracotta", name = "Red Terracotta", stackSize = 64, raw = false),
        Item(id = "black_terracotta", name = "Black Terracotta", stackSize = 64, raw = false),
        Item(id = "hay_bale", name = "Hay Bale", stackSize = 64, raw = false),
        Item(id = "white_carpet", name = "White Carpet", stackSize = 64, raw = false),
        Item(id = "orange_carpet", name = "Orange Carpet", stackSize = 64, raw = false),
        Item(id = "magenta_carpet", name = "Magenta Carpet", stackSize = 64, raw = false),
        Item(id = "light_blue_carpet", name = "Light Blue Carpet", stackSize = 64, raw = false),
        Item(id = "yellow_carpet", name = "Yellow Carpet", stackSize = 64, raw = false),
        Item(id = "lime_carpet", name = "Lime Carpet", stackSize = 64, raw = false),
        Item(id = "pink_carpet", name = "Pink Carpet", stackSize = 64, raw = false),
        Item(id = "gray_carpet", name = "Gray Carpet", stackSize = 64, raw = false),
        Item(id = "light_gray_carpet", name = "Light Gray Carpet", stackSize = 64, raw = false),
        Item(id = "cyan_carpet", name = "Cyan Carpet", stackSize = 64, raw = false),
        Item(id = "purple_carpet", name = "Purple Carpet", stackSize = 64, raw = false),
        Item(id = "blue_carpet", name = "Blue Carpet", stackSize = 64, raw = false),
        Item(id = "brown_carpet", name = "Brown Carpet", stackSize = 64, raw = false),
        Item(id = "green_carpet", name = "Green Carpet", stackSize = 64, raw = false),
        Item(id = "red_carpet", name = "Red Carpet", stackSize = 64, raw = false),
        Item(id = "black_carpet", name = "Black Carpet", stackSize = 64, raw = false),
        Item(id = "terracotta", name = "Terracotta", stackSize = 64, raw = false),
        Item(id = "packed_ice", name = "Packed Ice", stackSize = 64, raw = false),
        Item(id = "acacia_stairs", name = "Acacia Stairs", stackSize = 64, raw = false),
        Item(id = "dark_oak_stairs", name = "Dark Oak Stairs", stackSize = 64, raw = false),
        Item(id = "dirt_path", name = "Dirt Path", stackSize = 64, raw = true),
        Item(id = "sunflower", name = "Sunflower", stackSize = 64, raw = true),
        Item(id = "lilac", name = "Lilac", stackSize = 64, raw = true),
        Item(id = "rose_bush", name = "Rose Bush", stackSize = 64, raw = false),
        Item(id = "peony", name = "Peony", stackSize = 64, raw = true),
        Item(id = "tallgrass", name = "Tallgrass", stackSize = 64, raw = true),
        Item(id = "large_fern", name = "Large Fern", stackSize = 64, raw = true),
        Item(id = "white_stained_glass", name = "White Stained Glass", stackSize = 64, raw = false),
        Item(id = "orange_stained_glass", name = "Orange Stained Glass", stackSize = 64, raw = false),
        Item(id = "magenta_stained_glass", name = "Magenta Stained Glass", stackSize = 64, raw = false),
        Item(id = "light_blue_stained_glass", name = "Light Blue Stained Glass", stackSize = 64, raw = false),
        Item(id = "yellow_stained_glass", name = "Yellow Stained Glass", stackSize = 64, raw = false),
        Item(id = "lime_stained_glass", name = "Lime Stained Glass", stackSize = 64, raw = false),
        Item(id = "pink_stained_glass", name = "Pink Stained Glass", stackSize = 64, raw = false),
        Item(id = "gray_stained_glass", name = "Gray Stained Glass", stackSize = 64, raw = false),
        Item(id = "light_gray_stained_glass", name = "Light Gray Stained Glass", stackSize = 64, raw = false),
        Item(id = "cyan_stained_glass", name = "Cyan Stained Glass", stackSize = 64, raw = false),
        Item(id = "purple_stained_glass", name = "Purple Stained Glass", stackSize = 64, raw = false),
        Item(id = "blue_stained_glass", name = "Blue Stained Glass", stackSize = 64, raw = false),
        Item(id = "brown_stained_glass", name = "Brown Stained Glass", stackSize = 64, raw = false),
        Item(id = "green_stained_glass", name = "Green Stained Glass", stackSize = 64, raw = false),
        Item(id = "red_stained_glass", name = "Red Stained Glass", stackSize = 64, raw = false),
        Item(id = "black_stained_glass", name = "Black Stained Glass", stackSize = 64, raw = false),
        Item(id = "white_stained_glass_pane", name = "White Stained Glass Pane", stackSize = 64, raw = false),
        Item(id = "orange_stained_glass_pane", name = "Orange Stained Glass Pane", stackSize = 64, raw = false),
        Item(id = "magenta_stained_glass_pane", name = "Magenta Stained Glass Pane", stackSize = 64, raw = false),
        Item(id = "light_blue_stained_glass_pane", name = "Light Blue Stained Glass Pane", stackSize = 64, raw = false),
        Item(id = "yellow_stained_glass_pane", name = "Yellow Stained Glass Pane", stackSize = 64, raw = false),
        Item(id = "lime_stained_glass_pane", name = "Lime Stained Glass Pane", stackSize = 64, raw = false),
        Item(id = "pink_stained_glass_pane", name = "Pink Stained Glass Pane", stackSize = 64, raw = false),
        Item(id = "gray_stained_glass_pane", name = "Gray Stained Glass Pane", stackSize = 64, raw = false),
        Item(id = "light_gray_stained_glass_pane", name = "Light Gray Stained Glass Pane", stackSize = 64, raw = false),
        Item(id = "cyan_stained_glass_pane", name = "Cyan Stained Glass Pane", stackSize = 64, raw = false),
        Item(id = "purple_stained_glass_pane", name = "Purple Stained Glass Pane", stackSize = 64, raw = false),
        Item(id = "blue_stained_glass_pane", name = "Blue Stained Glass Pane", stackSize = 64, raw = false),
        Item(id = "brown_stained_glass_pane", name = "Brown Stained Glass Pane", stackSize = 64, raw = false),
        Item(id = "green_stained_glass_pane", name = "Green Stained Glass Pane", stackSize = 64, raw = false),
        Item(id = "red_stained_glass_pane", name = "Red Stained Glass Pane", stackSize = 64, raw = false),
        Item(id = "black_stained_glass_pane", name = "Black Stained Glass Pane", stackSize = 64, raw = false),
        Item(id = "prismarine", name = "Prismarine", stackSize = 64, raw = false),
        Item(id = "prismarine_bricks", name = "Prismarine Bricks", stackSize = 64, raw = false),
        Item(id = "dark_prismarine", name = "Dark Prismarine", stackSize = 64, raw = false),
        Item(id = "prismarine_stairs", name = "Prismarine Stairs", stackSize = 64, raw = false),
        Item(id = "prismarine_brick_stairs", name = "Prismarine Brick Stairs", stackSize = 64, raw = false),
        Item(id = "dark_prismarine_stairs", name = "Dark Prismarine Stairs", stackSize = 64, raw = false),
        Item(id = "sea_lantern", name = "Sea Lantern", stackSize = 64, raw = false),
        Item(id = "red_sandstone", name = "Red Sandstone", stackSize = 64, raw = false),
        Item(id = "chiseled_red_sandstone", name = "Chiseled Red Sandstone", stackSize = 64, raw = false),
        Item(id = "cut_red_sandstone", name = "Cut Red Sandstone", stackSize = 64, raw = false),
        Item(id = "red_sandstone_stairs", name = "Red Sandstone Stairs", stackSize = 64, raw = false),
        Item(id = "magma_block", name = "Magma Block", stackSize = 64, raw = false),
        Item(id = "nether_wart_block", name = "Nether Wart Block", stackSize = 64, raw = false),
        Item(id = "warped_wart_block", name = "Warped Wart Block", stackSize = 64, raw = false),
        Item(id = "red_nether_bricks", name = "Red Nether Bricks", stackSize = 64, raw = false),
        Item(id = "bone_block", name = "Bone Block", stackSize = 64, raw = false),
        Item(id = "shulkerbox", name = "Shulkerbox", stackSize = 1, raw = false),
        Item(id = "white_shulkerbox", name = "White Shulkerbox", stackSize = 1, raw = false),
        Item(id = "orange_shulkerbox", name = "Orange Shulkerbox", stackSize = 1, raw = false),
        Item(id = "magenta_shulkerbox", name = "Magenta Shulkerbox", stackSize = 1, raw = false),
        Item(id = "light_blue_shulkerbox", name = "Light Blue Shulkerbox", stackSize = 1, raw = false),
        Item(id = "yellow_shulkerbox", name = "Yellow Shulkerbox", stackSize = 1, raw = false),
        Item(id = "lime_shulkerbox", name = "Lime Shulkerbox", stackSize = 1, raw = false),
        Item(id = "pink_shulkerbox", name = "Pink Shulkerbox", stackSize = 1, raw = false),
        Item(id = "gray_shulkerbox", name = "Gray Shulkerbox", stackSize = 1, raw = false),
        Item(id = "light_gray_shulkerbox", name = "Light Gray Shulkerbox", stackSize = 1, raw = false),
        Item(id = "cyan_shulkerbox", name = "cyan_shulkerbox", stackSize = 1, raw = false),
        Item(id = "purple_shulkerbox", name = "Purple Shulkerbox", stackSize = 1, raw = false),
        Item(id = "blue_shulkerbox", name = "Blue Shulkerbox", stackSize = 1, raw = false),
        Item(id = "brown_shulkerbox", name = "Brown Shulkerbox", stackSize = 1, raw = false),
        Item(id = "green_shulkerbox", name = "Green Shulkerbox", stackSize = 1, raw = false),
        Item(id = "red_shulkerbox", name = "Red Shulkerbox", stackSize = 1, raw = false),
        Item(id = "black_shulkerbox", name = "Black Shulkerbox", stackSize = 1, raw = false),
        Item(id = "white_glazed_terracotta", name = "White Glazed Terracotta", stackSize = 64, raw = false),
        Item(id = "orange_glazed_terracotta", name = "Orange Glazed Terracotta", stackSize = 64, raw = false),
        Item(id = "magenta_glazed_terracotta", name = "Magenta Glazed Terracotta", stackSize = 64, raw = false),
        Item(id = "light_blue_glazed_terracotta", name = "Light Blue Glazed Terracotta", stackSize = 64, raw = false),
        Item(id = "yellow_glazed_terracotta", name = "Yellow Glazed Terracotta", stackSize = 64, raw = false),
        Item(id = "lime_glazed_terracotta", name = "Lime Glazed Terracotta", stackSize = 64, raw = false),
        Item(id = "pink_glazed_terracotta", name = "Pink Glazed Terracotta", stackSize = 64, raw = false),
        Item(id = "gray_glazed_terracotta", name = "Gray Glazed Terracotta", stackSize = 64, raw = false),
        Item(id = "light_gray_glazed_terracotta", name = "Light Gray Glazed Terracotta", stackSize = 64, raw = false),
        Item(id = "cyan_glazed_terracotta", name = "Cyan Glazed Terracotta", stackSize = 64, raw = false),
        Item(id = "purple_glazed_terracotta", name = "Purple Glazed Terracotta", stackSize = 64, raw = false),
        Item(id = "blue_glazed_terracotta", name = "Blue Glazed Terracotta", stackSize = 64, raw = false),
    )
}